## @file
# Assign reviewers from a REVIEWERS file using CODEOWNERS syntax
#
# Copyright (c) 2022, Intel Corporation. All rights reserved.<BR>
# SPDX-License-Identifier: BSD-2-Clause-Patent
##

name: 'Assign Reviewers'

description: Assign reviewers from a REVIEWERS file using CODEOWNERS syntax

inputs:
  token:
    description: token used to update PR reviewers
    required: true
    default: ''
  reviewers_path:
    description: path to REVIEWERS file if not in supported default locations.
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Checkout Assign Reviewers Repository
      uses: actions/checkout@v2
      with:
        repository: mdkinney/github-action-assign-reviewers
        ref: main
        path: ./AssignReviewersRepo
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        cache: 'pip'
        cache-dependency-path: '${{ github.action_path }}/pip-requirements.txt'
    - name: Install Python Dependencies
      run: pip install -r ${{ github.action_path }}/pip-requirements.txt
      shell: bash
    - name: Assign Reviewers from REVIEWERS file
      run: python ${{ github.action_path }}/src/AssignReviewers.py
      env:
        INPUT_TOKEN: ${{ inputs.token }}
        INPUT_REVIEWERS_PATH: ${{ inputs.reviewers_path }}
      shell: bash
