## @file
# Assign reviewers from .github/REVIEWERS using CODEOWNERS syntax
#
# Copyright (c) 2022, Intel Corporation. All rights reserved.<BR>
# SPDX-License-Identifier: BSD-2-Clause-Patent
##

name: 'Assign Reviewers'
description: Assign reviewers from .github/REVIEWERS using CODEOWNERS syntax
inputs:
  token:
    description: TOKEN
    required: true
    default: ''
runs:
  using: 'composite'
  steps:
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        cache: 'pip'
        cache-dependency-path: 'pip-requirements.txt'
    - name: Install Dependencies
      run: pip install -r pip-requirements.txt
      shell: bash
    - name: Assign Reviewers from .github/REVIEWERS
      run: python src/AssignReviewers.py
      shell: bash
    - name: Done
      run: echo Done
      shell: bash
